### ISSUE TITLE
no such file crash when using umap2

### ISSUE THREAD

**Issue by lucasduffey** [BinyaminSharet/Mtp#1]
```
[ALWAYS] Testing support: mtp
[INFO  ] Loading USB device mtp
[ERROR ] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/umap2/apps/scan.py", line 51, in run
    device = self.load_device(device_name, phy)
  File "/usr/local/lib/python2.7/dist-packages/umap2/apps/base.py", line 91, in load_device
    dev = usb_device(self, phy, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/umap2/dev/mtp.py", line 184, in __init__
    USBMtpInterface(app, phy)
  File "/usr/local/lib/python2.7/dist-packages/umap2/dev/mtp.py", line 80, in __init__
    self.object = MtpObject.from_fs_recursive('mtp_fs')
  File "build/bdist.linux-x86_64/egg/mtpdevice/mtp_object.py", line 174, in from_fs_recursive
    obj = MtpObject.from_file(path)
  File "build/bdist.linux-x86_64/egg/mtpdevice/mtp_object.py", line 186, in from_file
    raise Exception('there is no file/dir at %s' % os.path.abspath(path))
Exception: there is no file/dir at /home/username/research/umap2/mtp_fs
```

**Comment by lucasduffey** [comment]
solution: make the folder
